function [] = WriteResultFile(trialNo, response)
%Writes out the randomization of a TM_Trial
%Makes it a little easier for humans to read...
global parameters


% Write trial result to file:
fprintf(parameters.datafilepointer,'%i, %i, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s \n',...
    parameters.subNo,...
    trialNo, ...
    char(parameters.Item(trialNo)),...
    char(parameters.Contrast(trialNo)),...
    char(parameters.Type_Target(trialNo)),...
    char(parameters.Target(trialNo)),...
    char(parameters.Distractor(trialNo)),...
    char(parameters.Cohort(trialNo)),...
    char(parameters.SignerID(trialNo)),...
    char(parameters.TargetMoviePath(trialNo)),...
    char(parameters.DistractorMoviePath(trialNo)),...
    response);  


end