function Write_Trial_to_File(i)
%Wraps up the writing of this specific experiment's info
%i = trialno

global parameters

WriteResultFile({parameters.subNo,...
            datestr(now,'dd-mmm-yyyy'),...
            datestr(now,'HH:MM:SS.FFF'),...
            parameters.amyFileName(i),...
            i,...
            parameters.itemID(i),...
            parameters.verbName(i),...
            parameters.verbMeaning(i),...
            parameters.mannerSideBias(i),...
            parameters.pathSideBias(i),...
            parameters.biasTestAns(i),...
            parameters.mannerSideFinal(i),...
            parameters.pathSideFinal(i),...
            parameters.finalTestAns(i),...
            parameters.noun1TestAns,...
            parameters.noun2TestAns,...
            parameters.totalTime,...
            'xxxx',... %Marks a point after which the rest of the
                        %data is just for completion, interesting 
                        %stuff is above the line
            parameters.expStart,...
            parameters.trainStart(i),...
            parameters.trainEnd(i),...
            parameters.finalTestStart(i),...
            parameters.finalTestEnd(i),...
            parameters.ambigV(i),...
            parameters.mBiasV(i),...
            parameters.pBiasV(i),...
            parameters.trainV1(i),...
            parameters.trainV2(i),...
            parameters.trainV3(i),...
            parameters.mTestV(i),...
            parameters.pTestV(i),...
            parameters.ambigAudioFuture(i),...
            parameters.ambigAudioPast(i),...
            parameters.trainAudioFuture1(i),...
            parameters.trainAudioPast1(i),...
            parameters.trainAudioFuture2(i),...
            parameters.trainAudioPast2(i),...
            parameters.trainAudioFuture3(i),...
            parameters.trainAudioPast3(i),...
            parameters.whichOneAudio(i),...
            parameters.letsFindAudio(i)});
